### ISSUE TITLE
Consistent German language and meaningful error messages on the "Meine Bewerbungen"- page 💰 1

### ISSUE THREAD

**Issue by Helene0** [hpi-swt2/workshop-portal#148]
**As** 
user 

**I want to** 
have consistent german language on the "Meine Bewerbungen" page (pupil view) and meaningful error messages

**in order to** 
have a great user experience. 

This is an important issue for the already existing system. In the future we expect this to be considered throughout the new features.

- [ ] There is no mix of languages for names of input fields, error messages and the like
- [ ] I get error messages that explain what went wrong and what i can do to fix it

**Comment by radscheit** [comment]
@julisa99 @h0rnyc0rny Done, but:

- There was only one message to translate: the js alert confirmation dialogue. (Right?) But you should have in mind that the common dialogue buttons in the alert window are not translatable since the clients browser is providing them. So it depends on the clients themselves and their browsers in which language the buttons in the alert window will appear - mostly they will appear in german. But if you wish to ensure that, we have to get rid of JS alerts in general, but I would suggest to put this into another user story.  
- I added some translations for the application letters edit action regarding the pupils perspective, because #147 is only taking care of the coach/organizer perspective.
