### ISSUE TITLE
US_1.22: Anfragen Overview page

### ISSUE THREAD

**Issue by Helene0** [hpi-swt2/workshop-portal#218]
**As** 
organizer/coach
 
**I want to** 
have an overview page where I see all existing requests for workshops with the topic wish, the name of the person that made the request, the date wish and the and amount of people that would participate. I also want to see a status that shows if the request is open or accepted. I want a details button!

**in order to** 
have better overview

** 🍪**
- [ ]

**Comment by tom95** [comment]
Note: the overview of requests should only be visible to organizers (and coaches?) and in any case not be displayed for people that are not logged in. Ideally we would adapt the access rules, as well as the navbar accordingly as part of this US, displaying "Anfrage stellen" that links to `requests_new_path` instead of "Anfragen" linking to `requests_path` when someone without the necessary rights visits the site.
