### ISSUE TITLE
Button Removal Party

### ISSUE THREAD

**Issue by julisa99** [hpi-swt2/workshop-portal#272]
**As**
user

**I DONT want to**
have "Abbrechen" buttons all over the place that lead me to secret paths

**in order to**
have a structured navigation of the page and know where I am 

# Acceptance criteria
- [x] buttons on the following sites are removed:
 - [x] Profil erstellen/bearbeiten
 - [x] Veranstaltungseite für Organiser
 - [x] Veranstaltungseite für User
 - [x] Veranstaltung bearbeiten
 - [x] Event erstellen
 - [x] Anfrage stellen
 - [x] Einstellungen (nur Link)
 - [x] Profil bearbeiten

**Comment by bjrne** [comment]
If the button "Abbrechen" is removed from the "Profil bearbeiten" Page, how am I supposed to move back? I'd have to select the navbar dropdown, chose an item, search for that user and go to his/her details? @julisa99 @Helene0

**Comment by LeaGe** [comment]
@Helene0 was ist mit "Einstellungen (nur Link)" gemeint? die einstellungen unter dem drop-down beim user?

**Comment by Helene0** [comment]
Genau, das ist gemeint.

**Comment by julisa99** [comment]
@bjrne with the browser back button

**Comment by bjrne** [comment]
@julisa99 Okay, I understand that. But for me personally, the browser back button isn't so trustworthy with visible editable fields. As a user I can never be sure what happens if I edited a field, didn't click save and want the change gone. A discard button has a clear semantic meaning to it, while the back button does not because websites respond to it in different ways. But we'll continue with your decision and see how it works out.
