### ISSUE TITLE
Forgot Password functionality does not work

### ISSUE THREAD

**Issue by cmfcmf** [hpi-swt2/workshop-portal#299]
If you try to use the forgot password functionality, after sending the form, the page errors out. 

@hpi-swt2/scrum-master-2016

**Comment by Helene0** [comment]
**As**
user

**I want to**
be able to click the Passwort vergessen button and enter my E-mail adress so that I get an E-Mail that enables me to set a new password in a secure way on the page (for example with a 24 hour token or something equally safe and easy to use)

**In order to**
still be able to use the platform even if i forgot it

**Comment by tom95** [comment]
Testing this locally, it worked flawlessly. Maybe mail transport is just not properly configured on dev or where did you test it?

**Comment by cmfcmf** [comment]
Yes, this was tested on Heroku-dev.
