### ISSUE TITLE
Pictures Upload

### ISSUE THREAD

**Issue by Helene0** [hpi-swt2/workshop-portal#320]
**As**
organizer

**I want to**
be able to upload pictures for workshops and events

**In order to**
make it all veeeery pretty

**Acceptance Criteria:**
- [ ] I have an upload option on the Veranstaltung erstellen Page where I can upload the needed pictures and it tells me what sizes are needed
- [x] I get an error when I upload something too small
- [x]  scale proportionally on start page
- [ ] scale proportionally on event edit page
- [ ] ensure, that added images stay connected with the event event when when a validation fails.

**Comment by tobiasduerschmid** [comment]
@corinnaj: Could you please scale down the image proportionally on the event edit page, too?

Furthermore, when I upload an image during the creation of the event, submit the creation but get an error (e.g. one mandatory field is empty), correct the mistake and finally submit the event, the image is not added to the event. Please ensure, that added images stay connected with the event event when when a validation fails. 

The AC "it tells me what sizes are needed" is not fulfilled, since I get the error message not before submitting the event

**Comment by corinnaj** [comment]
The requested additions are being addressed in PR #577.

**Comment by hendraet** [comment]
:lips:
