### ISSUE TITLE
Angenommene Workshop Anfragen auf Veranstaltungsseite

### ISSUE THREAD

**Issue by Helene0** [hpi-swt2/workshop-portal#384]
Nur sichtbar für Orga auf Veranstaltungsseite

**Comment by bjrne** [comment]
@julisa99 can you add a reference to the other issue? I couldn't find it.

**Comment by julisa99** [comment]
@hendraet I can only find https://github.com/hpi-swt2/workshop-portal/issues/364
Do you wanted to discuss it with the UI team or whats the number of the issue?

**Comment by hendraet** [comment]
@julisa99 @bjrne #341 there you gooohoo :wink:

**Comment by bjrne** [comment]
@hendraet @julisa99 To me these are two different features. Seeing accepted requests from teachers on the event page in order to see all upcoming dates is one thing, being able to hide workshops in order for only letting specific applicants apply is another. Is the latter one enough or is there a misunderstanding?

**Comment by hendraet** [comment]
@bjrne Accepted request are not automatically shown on the event overview page. That is because if a request gets accepted the responsible organizer should also create the according hidden event (so we can get the data of the pupils). This event is then shown on the event overview page.
