### ISSUE TITLE
Login Error Rework

### ISSUE THREAD

**Issue by hendraet** [hpi-swt2/workshop-portal#429]
**Acceptance Criteria**
- [ ] error on failed login should always say: "E-Mail-Adresse oder Passwort ungültig."

*Reason*: The way it is atm one could find out wihch mails are registered in the system depending on the error message

**Comment by bjrne** [comment]
@hpi-swt2/product-owner-2016 @nstrelow fixed this in [here](https://github.com/hpi-swt2/workshop-portal/blob/dev/config/initializers/devise.rb#L78). Are you sure this is still the case?

**Comment by hendraet** [comment]
@bjrne This isn't what Nils fixed. The problem is that if you type in an incorrect mail address you get "E-Mail-Adresse oder Passwort ungültig.". 
If the mail address is correct it says: "Ungültige Anmeldedaten."
This shouldn't be the case

**Comment by bjrne** [comment]
Ah okay, i thought it was. Alright then :)

**Comment by nstrelow** [comment]
I set the devise paranoid mode. This should make all email queries, so that no one can find out what emails are in the system.

I assume that the string "Ungültige Anmeldedaten" is used by us and is not the default devise string.

So a solution should be to change to string we defined ourselves to the one used for devise.

**Comment by hendraet** [comment]
:raised_hands:
