### ISSUE TITLE
Event creation form does not have the red stars for required fields

### ISSUE THREAD

**Issue by cmfcmf** [hpi-swt2/workshop-portal#510]
It is unclear which fields are required.

@hpi-swt2/product-owner-2016

**Comment by bjrne** [comment]
@cmfcmf This is due to the problem of validating when saving an event draft. Some fields used to be mandatory, but we added events drafts and removed the required fields because it wasn't worth the effort at the time (You'd have to enter something in every required field which is kinda the opposite of what you want when drafting an event). If this has changed in the meantime, the POs should give it a priority rating.

**Comment by cmfcmf** [comment]
Events do still have required fields, for example the maximum number of participants.
