### ISSUE TITLE
Newlines in Motivation Letters

### ISSUE THREAD

**Issue by tobiasduerschmid** [hpi-swt2/workshop-portal#615]
**As**
applicant

**I want to**
add new lines in my letter of motivation

**In order to**
structure it accordingly.

# Acceptance criteria

- new lines added in the field for letter of motivation is displayed on the application checking page and the application detail page.

**Comment by son-vyas** [comment]
@tobiasduerschmid  Is this issue still on going? I would love to give this a go.

**Comment by annkatrinkuessner** [comment]
Hi @son-vyas, yes, this issue is still ongoing. 
We're a student group from the same university
 We are still working on this project, but over the summer break we have not been meeting all that often ;-)
You can find our workflow in the wiki: https://github.com/hpi-schuelerklub/workshop-portal/wiki/Workflow. 
If you have any questions just let us know.

**Comment by querenker** [comment]
Hey @son-vyas, are you still interested in this issue? If you encounter any problems please let us know. We are very interested to make contributions to this project as easy as possible, so your feedback would be very valuable for us :)
